CREATE SEQUENCE IF NOT EXISTS client_seq START WITH 1 INCREMENT BY 1;
ALTER TABLE client ALTER COLUMN id INT DEFAULT NEXT VALUE FOR client_seq;
CREATE SEQUENCE IF NOT EXISTS ticket_seq START WITH 1 INCREMENT BY 1;
ALTER TABLE ticket ALTER COLUMN id INT DEFAULT NEXT VALUE FOR ticket_seq;